var MENU_DATA = [
  {
    라벨: '메인',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '메인',
        링크: 'main_1',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '로그인',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '로그인',
        링크: 'login_1',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '아이디찾기',
        링크: 'login_2',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '비밀번호찾기',
        링크: 'login_3',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '회원가입',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '약관동의',
        링크: 'join_1',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '회원가입 양식 입력',
        링크: 'join_2',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '퍼블리싱 가이드',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '테스트',
        링크: '_pub_test',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '커스텀 UI',
        링크: '',
        보임: true,
        상태: '',
        자식: [
          {
            라벨: 'Header',
            링크: '_pub_header',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Footer',
            링크: '_pub_footer',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '컴포넌트',
            링크: '_pub_component',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '폼',
            링크: '_pub_form',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '텍스트 인풋',
            링크: '_pub_input',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '셀렉트',
            링크: '_pub_select',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '버튼',
            링크: '_pub_button',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '레이어 팝업',
            링크: '_pub_layerpop',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Alert 또는 Confirm',
            링크: '_pub_alert',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '바텀시트',
            링크: '_pub_bottom_sheet',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'iOS 스타일 셀렉트',
            링크: '_pub_ios_select',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Full Page Swiper',
            링크: '_pub_fullpage',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'CSS Scroll Snap',
            링크: '_pub_scroll_snap',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Fixed & Sticky',
            링크: '_pub_fixed',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Wheel Down Horizontal Scroll',
            링크: '_pub_wheel_hscroll',
            보임: true,
            상태: '',
            자식: [],
          },
        ],
      },
      {
        라벨: '라이브러리 샘플링',
        링크: '',
        보임: true,
        상태: '',
        자식: [
          {
            라벨: 'Swiperjs',
            링크: '_pub_swiper',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Accordion',
            링크: '_pub_accordion',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'AOS',
            링크: '_pub_aos',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Plyr',
            링크: '_pub_plyr',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'AutoComplete.js',
            링크: '_pub_auto_complete',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Particles.js',
            링크: '_pub_particles',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'SortableJS',
            링크: '_pub_sortablejs',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Flatpickr',
            링크: '_pub_flatpickr',
            보임: true,
            상태: '',
            자식: [],
          },
        ],
      },
    ],
  },
  {
    라벨: '라이브러리 공식 홈페이지',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: 'Swiper - 슬라이드',
        링크: 'https://swiperjs.com/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '카카오맵',
        링크: 'https://apis.map.kakao.com/web/guide/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'Accordion - 아코디언',
        링크: 'https://michu2k.github.io/Accordion/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'AOS - 스크롤 반응 애니메이션',
        링크: 'http://michalsnik.github.io/aos/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'Plyr - 비디오 플레이어',
        링크: 'https://plyr.io/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'autoComplete.js - 자동완성',
        링크: 'https://tarekraafat.github.io/autoComplete.js/#/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'panzoom - 확대, 축소, 드래그 스크롤',
        링크: 'https://timmywil.com/panzoom/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'particles.js - 파티클',
        링크: 'https://vincentgarreau.com/particles.js/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'SortableJS - 리스트 드래그',
        링크: 'https://sortablejs.github.io/Sortable/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'flatpickr - 데이트피커',
        링크: 'https://flatpickr.js.org/',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
];
