var MENU_DATA = [
  {
    라벨: '메인',
    페이지명: '',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '메인',
        페이지명: 'main_1',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '로그인',
    페이지명: '',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '로그인',
        페이지명: 'login_1',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '아이디찾기',
        페이지명: 'login_2',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '비밀번호찾기',
        페이지명: 'login_3',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '회원가입',
    페이지명: '',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '약관동의',
        페이지명: 'join_1',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '회원가입 양식 입력',
        페이지명: 'join_2',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
  {
    라벨: '퍼블리싱 가이드',
    페이지명: '',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: '테스트',
        페이지명: '_pub_test',
        링크: '',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '커스텀 UI',
        페이지명: '',
        링크: '',
        보임: true,
        상태: '',
        자식: [
          {
            라벨: 'Header',
            페이지명: '_pub_header',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Footer',
            페이지명: '_pub_footer',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Component',
            페이지명: '_pub_component',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Text Input',
            페이지명: '_pub_input',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Select',
            페이지명: '_pub_select',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Dropdown',
            페이지명: '_pub_dropdown',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Button',
            페이지명: '_pub_button',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '체크박스',
            페이지명: '_pub_checkbox',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '라디오버튼',
            페이지명: '_pub_radiobutton',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '레이어 팝업',
            페이지명: '_pub_layerpop',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Alert 또는 Confirm',
            페이지명: '_pub_alert',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: '바텀시트',
            페이지명: '_pub_bottom_sheet',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Full Page Swiper',
            페이지명: '_pub_fullpage',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'CSS Scroll Snap',
            페이지명: '_pub_scroll_snap',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Fixed & Sticky',
            페이지명: '_pub_fixed',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Wheel Down Horizontal Scroll',
            페이지명: '_pub_wheel_hscroll',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
        ],
      },
      {
        라벨: '라이브러리 샘플링',
        페이지명: '',
        링크: '',
        보임: true,
        상태: '',
        자식: [
          {
            라벨: 'Swiperjs',
            페이지명: '_pub_swiper',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Accordion',
            페이지명: '_pub_accordion',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'AOS',
            페이지명: '_pub_aos',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Plyr',
            페이지명: '_pub_plyr',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'AutoComplete.js',
            페이지명: '_pub_auto_complete',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Particles.js',
            페이지명: '_pub_particles',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'SortableJS',
            페이지명: '_pub_sortablejs',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
          {
            라벨: 'Flatpickr',
            페이지명: '_pub_flatpickr',
            링크: '',
            보임: true,
            상태: '',
            자식: [],
          },
        ],
      },
    ],
  },
  {
    라벨: '라이브러리 공식 홈페이지',
    페이지명: '',
    링크: '',
    보임: true,
    상태: '',
    자식: [
      {
        라벨: 'UAParser.js - OS 및 브라우져 확인',
        페이지명: '',
        링크: 'https://uaparser.js.org/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'Swiper - 슬라이드',
        페이지명: '',
        링크: 'https://swiperjs.com/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: '카카오맵',
        페이지명: '',
        링크: 'https://apis.map.kakao.com/web/guide/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'Accordion - 아코디언',
        페이지명: '',
        링크: 'https://michu2k.github.io/Accordion/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'AOS - 스크롤 반응 애니메이션',
        페이지명: '',
        링크: 'http://michalsnik.github.io/aos/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'Plyr - 비디오 플레이어',
        페이지명: '',
        링크: 'https://plyr.io/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'autoComplete.js - 자동완성',
        페이지명: '',
        링크: 'https://tarekraafat.github.io/autoComplete.js/#/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'panzoom - 확대, 축소, 드래그 스크롤',
        페이지명: '',
        링크: 'https://timmywil.com/panzoom/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'particles.js - 파티클',
        페이지명: '',
        링크: 'https://vincentgarreau.com/particles.js/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'SortableJS - 리스트 드래그',
        페이지명: '',
        링크: 'https://sortablejs.github.io/Sortable/',
        보임: true,
        상태: '',
        자식: [],
      },
      {
        라벨: 'flatpickr - 데이트피커',
        페이지명: '',
        링크: 'https://flatpickr.js.org/',
        보임: true,
        상태: '',
        자식: [],
      },
    ],
  },
];
